version: 2
project_name: mosquitto-exporter
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["molpie/mosquitto-exporter:{{ .Tag }}-amd64"]
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/amd64"
- image_templates: ["molpie/mosquitto-exporter:{{ .Tag }}-arm64"]
  use: buildx
  build_flag_templates:
  - "--pull"
  - "--platform=linux/arm64"
  goarch: arm64
docker_manifests:
- name_template: 'molpie/mosquitto-exporter:{{ .Tag }}'
  image_templates:
  - 'molpie/mosquitto-exporter:{{ .Tag }}-amd64'
  - 'molpie/mosquitto-exporter:{{ .Tag }}-arm64'
changelog:
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "Build"
      regexp: '^.*?build(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test"
      - "^typo"
      - "^ci"
    include:
      - "^build"
      - "^feat"
      - "^fix"
      - "^perf"
      - "^refactor"
      - "^style"