FROM golang:1.24-bookworm AS build

WORKDIR /go/src/app

## Download modules and store, this optimizes use of Docker image cache
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN make build

FROM debian:trixie-slim
LABEL source_repository="https://github.com/jryberg/mosquitto-exporter"

COPY --from=build /go/src/app/bin/mosquitto_exporter /mosquitto_exporter
RUN apt update && \
    apt install -y ca-certificates
EXPOSE 9234

ENTRYPOINT [ "/mosquitto_exporter" ]
